# build environment
FROM node:latest as build
WORKDIR /app

# install app dependencies
COPY package.json ./

RUN npm install -g create-react-app@3.4.1
RUN npm i react-scripts
# install 
RUN npm install 
COPY . ./
ENV PATH /app/node_modules/.bin:$PATH
# build 
RUN yarn build

# production 
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]