version: '3.7'

services:

  ladybug-prod:
    container_name: ladybug-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'

# to run
# docker-compose -f docker-compose.prod.yml up --build